name: Python Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  python-tests:

    runs-on: ubuntu-18.04
    container: axsauze/kompute-builder:0.2

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: configure-python
      run: |
        pip3 install -r python/test/requirements-dev.txt
    - name: build-python
      run: |
        pip3 install .
    - name: test-python
      run: |
        export VK_ICD_FILENAMES=/swiftshader/vk_swiftshader_icd.json
        pytest -v python/test/test_array_multiplication.py
        pytest -v python/test/test_kompute.py -k "test_opmult"
        pytest -v python/test/test_kompute.py -k "test_tensor_rebuild_backwards_compat"
        pytest -v python/test/test_logistic_regression.py


